// This file is generated by build_runner. It should not be manually edited.
// Run: flutter pub run build_runner build

part of 'models.dart';

// *** GENERATED CODE STUB ***
// This is a placeholder for JSON serialization code that would be generated
// by the json_serializable package via build_runner.
//
// To generate the actual serialization code, run:
// flutter pub run build_runner build --delete-conflicting-outputs
//
// The generated code will include:
// - _$InterviewQuestionFromJson and _$InterviewQuestionToJson
// - _$CandidateResponseFromJson and _$CandidateResponseToJson
// - _$SkillMatchFromJson and _$SkillMatchToJson
// - _$RecommendationFromJson and _$RecommendationToJson
// - _$MatchReportFromJson and _$MatchReportToJson
// - _$AssessmentFromJson and _$AssessmentToJson

// TODO: Run build_runner to generate JSON serialization code
